checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  environment:
    python:
      version: '3.10.4'

      # Whether to setup a virtual environment in the repository root directory.
      # Defaults to true if omitted.
      virtualenv: true
  nodes:
    my-tests-with-coverage:
      tests:
        override:
          - command: pytest
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'