checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  environment:
    variables:
      CFLAGS: -I/usr/include/openssl
      LDFLAGS: -L/usr/lib
    python:
      version: '3.10.4'
      # version: '3.9.12'
      # Whether to setup a virtual environment in the repository root directory.
      # Defaults to true if omitted.
      virtualenv: true
  nodes:
    my-tests-with-coverage:
      tests:
        override:
          - command: pytest
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'