checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  environment:
    python:
      version: '3.9.12'
      virtualenv: true
  nodes:
    analysis:
      project_setup:
          override:
            - command: pip install -r test-requirements.txt
      tests:
        override:
          - command: pytest --cov=./
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'